### ISSUE TITLE
Incorrect Environment Variable Instructions for PowerShell 

### ISSUE THREAD

**Issue by timmyreilly** [Azure-Samples/azure-iot-samples-node#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
These instructions are do not work as expected for PowerShell:
https://github.com/Azure-Samples/azure-iot-samples-node/tree/master/iot-hub/Samples/device

 
### Minimal steps to reproduce
> Try to run the send_telemetry.js samples in VS Code with powershell after following the instructions provided for setting Environment Variables

### Suggestion: 
Change the readme to add proper environment variable settings for powershell: 

eg: `$env:DEVICE_CONNECTION_STRING="HostName=yourhub.azure-devices.net;DeviceId=scanner1;SharedAccessKey=asdfasdfasdf/dq9ef9FM9QkhBmGhyjXcmA="`
 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

**Comment by yzhong94** [comment]
@timmyreilly thank you for filing this issue!  We will hold off on adding instruction on environment variable since it varies depending on the OS.  This issue is a great documentation for folks running into the same issue though.
