### ISSUE TITLE
Error message when trying to run SimulatedDevice-1.js

### ISSUE THREAD

**Issue by rukmani-msft** [Azure-Samples/azure-iot-samples-node#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the tutorial in https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-node
Download the sample on to Macbook Pro from https://github.com/Azure-Samples/azure-iot-samples-node/archive/master.zip
Look for SimulatedDevice-1.js in azure-iot-samples-node-master/iot-hub/Tutorials/ConnectivityTests
ensure node is installed (version on my machine - v10.14.1
Update the connection string in SimulatedDevice-1.js
Run the file using node.

### Any log messages given by the failure
>
rukmanigopalan@Rukmanis-MacBook-Pro ConnectivityTests $ node SimulatedDevice-1.js 
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'azure-iot-device-mqtt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rukmanigopalan/Downloads/azure-iot-samples-node-master/iot-hub/Tutorials/ConnectivityTests/SimulatedDevice-1.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
rukmanigopalan@Rukmanis-MacBook-Pro ConnectivityTests $ 

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rukmani-msft** [comment]
FYI - as indicated in the tutorial , the zip file in the archive was used.

**Comment by dominicbetts** [comment]
@pierreca - I'll take a look to see what we can do.

**Comment by yzhong94** [comment]
@dominicbetts were the docs updated for npm install command?  Thanks!

**Comment by dominicbetts** [comment]
@yzhong94 - the article is quite explicit that you need to run `npm install` - see https://docs.microsoft.com/azure/iot-hub/quickstart-send-telemetry-node#send-simulated-telemetry

**Comment by yzhong94** [comment]
@dominicbetts great!  I will close this issue then since our docs are very explicit.  Thank you!
