### ISSUE TITLE
ENOTFOUND Hub.azure-devices.net Hub.azure-devices.net:5671

### ISSUE THREAD

**Issue by ablanco6** [Azure-Samples/azure-iot-samples-node#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run ReadDevicetoCloudMessages.js behind a proxy with correct proxy settings passed to the constructor:

EventHubClient.createFromIotHubConnectionString(connectionString, {webSocket: new HttpsProxyAgent(proxy)}).then(function (client) {
  console.log("Successfully created the EventHub Client from iothub connection string.");
  ehClient = client;
  return ehClient.getPartitionIds();
}).then(function (ids) {
  console.log("The partition ids are: ", ids);
  return ids.map(function (id) {
    return ehClient.receive(id, printMessage, printError, { eventPosition: EventPosition.fromEnqueuedTime(Date.now()) });
  });
}).catch(printError);
### Any log messages given by the failure
> ENOTFOUND Hub.azure-devices.net Hub.azure-devices.net:5671

### Expected/desired behavior
> To work as intended

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Linux Ubuntu 

### Versions
>18.04

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create a PR on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node) if you see value in this PR.
