### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module 'azure-iot-provisioning-device-mqtt'

### ISSUE THREAD

**Issue by hajiuduman** [Azure-Samples/azure-iot-samples-node#35]
Am developing a react app azure IOT simulator. Below is my code inside handleChange function

var iotc = new IoTCClient(deviceId, scopeId, 'symm_key', sasKey);
iotc.connect();

declared the below import stmt aswell.

import {IoTCClient} from 'azure-iotcentral-device-client';

But am getting below error

Uncaught (in promise) Error: Cannot find module 'azure-iot-provisioning-device-mqtt'
    at webpackEmptyContext (-.*$:2)
    at provision.ts:58
    at async DeviceProvisioning.getProvisionTransport (provision.ts:58)
    at async DeviceProvisioning.register (provision.ts:30)
    at async IoTCClient.register (iotcClient.ts:179)
    at async IoTCClient.connect (iotcClient.ts:128)

If I run the same code without react component (using node test.js) it is working fine.
but inside react component it is failing
all the dependency modules are installed

**Comment by anthonyvercolano** [comment]
The SDK does not currently support running inside of react.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create a PR on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node) if you see value in this PR.
