### ISSUE TITLE
ReadDeviceToCloudMessages throws Cannot read property 'fromConnectionString' of undefined

### ISSUE THREAD

**Issue by jeffaknine** [Azure-Samples/azure-iot-samples-node#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Using the ReadDeviceToCloudMessages, changing the connection string to my IoTHub's, i'm getting the following error:

### Any log messages given by the failure
>TypeError: Cannot read property 'fromConnectionString' of undefined
    at Object.<anonymous> (C:\Users\JeffAknine\Documents\Devoteam.SMARTOffice\webapi\ReadDeviceToCloudMessages.js:45:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

### Expected/desired behavior
>Creating a connection to the IoT Hub and being able to receive messages

### OS and Version?
> Windows 10

### Versions
> Node.js version 8.11.1

### Mention any other details that might be useful
I'm trying to follow the following guide : https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-node
When looking at the npm package i see that there is a different implementation for IoT hub connection. I'm not sure what to follow anymore
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pierreca** [comment]
@jeffaknine yes that's one option - this is what we will do when we get around updating the tutorials. the other option is to use the same code but manually install the older 0.0.8 version of the SDK using:
```
npm install azure-event-hubs@0.0.8
```

**Comment by jeffaknine** [comment]
Thanks a lot for your quick answers.
When using the example 6. i get a "getHubRuntimeInfo is not a function". Shouldn't it be "getHubRuntimeInformation" ?

**Comment by amarzavery** [comment]
@jeffaknine - Changes made in #6 should fix the issue.

**Comment by jeffaknine** [comment]
Thanks i'll check it out.

**Comment by amarzavery** [comment]
@jeffaknine #6 has been merged. Please feel free to close this issue, if the sample works fine for you.
