### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by domitix** [Azure-Samples/azure-iot-samples-node#40]
Hi, I'm creating a nodejs webapp that takes some values from the sensors and sends them to my Azure Iot Hub. When I run simulateddevice.js in local with random values it works perfectly, but when i run these commands inside the webapp, I have some issues. In particular, the console shows the message "require is not defined", even though I have installed it in my computer and it is also specified inside package.json. Do you know how to work this out? Thank you in advance

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create a PR on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node) if you see value in this PR.
