### ISSUE TITLE
Error: EBUSY: resource busy or locked, write

### ISSUE THREAD

**Issue by martignonia** [Azure-Samples/azure-iot-samples-node#43]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
git clone https://github.com/Azure-Samples/azure-iot-samples-node.git
cd azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp
npm install
nano config.json
sudo node index.js '<YOUR AZURE IOT HUB DEVICE CONNECTION STRING>'

### Any log messages given by the failure
>
node index.js "HostName=XXXX.azure-devices.net;DeviceId=myPi;SharedAccessKey=XXXXXXXXXXXXXX"
[Device] Using MQTT transport protocol
[Device] Sending message: {"messageId":1,"deviceId":"Raspberry Pi Node","temperature":28.42521097181653,"humidity":68.09248280578088}
/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
                        throw error;
                        ^

Error: EBUSY: resource busy or locked, write
    at Object.writeSync (fs.js:573:3)
    at Object.writeFileSync (fs.js:1204:26)
    at exportGpio (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/onoff/onoff.js:18:8)
    at new Gpio (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/onoff/onoff.js:172:36)
    at blinkLED (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/index.js:88:17)
    at client.sendEvent (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/index.js:44:9)
    at safeCallback (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device/dist/internal_client.js:33:9)
    at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device/dist/internal_client.js:134:17
    at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-common/dist/retry_operation.js:57:21
    at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device-mqtt/dist/mqtt.js:447:17

### Expected/desired behavior
>
uploading rows into Azure instance

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Raspberry Pi OS with desktop and recommended software

Release date: August 20th 2020
Kernel version: 5.4

### Versions
>
NA

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create a PR on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node) if you see value in this PR.
