### ISSUE TITLE
Clarify where to find Azure IoT samples for node

### ISSUE THREAD

**Issue by rido-min** [Azure-Samples/azure-iot-samples-node#46]
How is this repo related to https://github.com/Azure/azure-iot-sdk-node/tree/master/device/samples ? It has been updated recently, while this one has not been updated since Nov 2020, issues not triaged, etc..

**Comment by ryanwinter** [comment]
Closing as repository is being archived. Please create an Issue on [azure-iot-sdk-node](https://github.com/Azure/azure-iot-sdk-node) if you see value in this Issue.
